name: Build application

on: [push, pull_request]

jobs:
  windows-msvc-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure
      shell: bash
        mkdir -p ci-build
        cmake -B ci-build \
          -G "Visual Studio 18 2026" \
          -A x64 \
          -DCMAKE_CXX_STANDARD=20 \
          -DCMAKE_CXX_STANDARD_REQUIRED=ON \
          -DBUILD_TESTS=ON \
          -DBUILD_SAMPLES=ON
    
    - name: Run tests
      shell: bash
      run: |
        find ci-build -name "*test*.exe" -type f -exec {} --gtest_repeat=2 --gtest_break_on_failure \;